import type { Metadata } from 'next';
import { roboto, notoSansKr } from '@/style/font';
import '@/style/globals.scss';
import clsx from 'clsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(roboto.variable, notoSansKr.variable)}>
      <body>{children}</body>
    </html>
  );
}
